package com.oracle.xmlns.touresbalon.toures_sca.bpelprocesscancel;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2018-11-06T19:30:41.858-05:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/TouresBalon/toures_sca/BPELProcessCancel", name = "BPELProcessCancel")
@XmlSeeAlso({co.com.touresbalon.model.canonical._1_0.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BPELProcessCancel {

    @WebMethod(action = "process")
    @Oneway
    public void process(
        @WebParam(partName = "payload", name = "CancelOrderRequest", targetNamespace = "http://touresbalon.com.co/model/canonical/1.0.0")
        co.com.touresbalon.model.canonical._1_0.CancelOrderRequest payload
    );
}
